spring:
  application:
    name: login-system-fullstack
  profiles:
    active: dev

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:

      client:
        registration:
          keycloak:
            client-id:
            client-secret:
            scope: openid, profile, email

        provider:
          keycloak:
           issuer-uri:
server:
  port: 8080
  ssl:
    key-store:
    key-store-password:
    key-store-type:
    key-alias:
    key-password:
