spring:
  application:
    name: login-system-fullstack
  profiles:
    active: prd

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri:

      client:
        registration:
          keycloak:
            client-id:
            client-secret:
            scope:

        provider:
          keycloak:
           issuer-uri:
