spring:
  application:
    name: login-system-fullstack
  profiles:
    active: prd

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/robertolima

      client:
        registration:
          keycloak:
            client-id: Login-System-FullStack
            client-secret: 5iv0eagcqxiSpQ9xGWSusudbqjGKXyDb
            scope: openid, profile, email

        provider:
          keycloak:
           issuer-uri: http://localhost:8085/realms/robertolima
